import type { Metadata } from "next";
import { Zain } from 'next/font/google';

import "./globals.css";
// 1. استيراد المكونات التي أنشأناها
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";






// إعداد خط عربي (مثلاً Aref Ruqaa Ink لأنه يشبه طابع الحبر)
// إعداد خط Zain
const zain = Zain({
  subsets: ["arabic"],
  weight: ["300", "400", "700", "900"], // تحميل الأوزان المختلفة
  variable: "--font-zain", // تعريف المتغير
});




export const metadata: Metadata = {
  title: "بيت الود",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 2. تغيير اللغة للعربية وتحديد اتجاه النص من اليمين لليسار
    <html lang="ar" dir="rtl">
      <body className={`${zain.variable} antialiased`} suppressHydrationWarning>

        
        
        {/* 3. إضافة الناف بار في الأعلى ليظهر في كل الصفحات */}
        <Navbar />

        {/* 4. تغليف المحتوى بـ main لضمان تنظيم المساحات */}
        <main className="min-h-screen">
          {children}
        </main>

        {/* 5. إضافة الفوتر في الأسفل ليظهر في كل الصفحات */}
        <Footer />
        
      </body>
    </html>
  );
}
